<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view-profile',
            'view-user',
            'create-user',
            'edit-user',
            'delete-user',
            'show-user',
            'restore-user',
            'force-delete-user',
            'bulk-delete-user',
            'force-bulk-delete-user',
            'view-chart-user',
            'view-role',
            'create-role',
            'edit-role',
            'delete-role',
            'show-role',
            'bulk-delete-role',
            'view-permission',
            'create-permission',
            'edit-permission',
            'delete-permission',
            'show-permission',
            'bulk-delete-permission',
            'view-trash-group-button',
            'view-backup-database',
            'view-department',
            'create-department',
            'edit-department',
            'delete-department',
            'show-department',
            'bulk-delete-department',
            'import-department',
            'export-department',
            'view-branch',
            'create-branch',
            'edit-branch',
            'delete-branch',
            'show-branch',
            'bulk-delete-branch',
            'import-branch',
            'export-branch',
            'view-chart-branch',
            'view-patch',
            'create-patch',
            'edit-patch',
            'delete-patch',
            'bulk-delete-patch',
            'import-patch',
            'export-patch',
            'view-chart-patch',
            'view-switch',
            'create-switch',
            'edit-switch',
            'delete-switch',
            'bulk-delete-switch',
            'import-switch',
            'export-switch',
            'view-chart-switch',
            'view-ip',
            'create-ip',
            'edit-ip',
            'delete-ip',
            'bulk-delete-ip',
            'import-ip',
            'export-ip',
            'view-chart-ip',
            'view-company',
            'create-company',
            'edit-company',
            'delete-company',
            'bulk-delete-company',
            'import-company',
            'export-company',
            'view-rack',
            'create-rack',
            'edit-rack',
            'delete-rack',
            'bulk-delete-rack',
            'import-rack',
            'export-rack',
            'view-chart-rack',
            'view-subnet',
            'create-subnet',
            'edit-subnet',
            'delete-subnet',
            'bulk-delete-subnet',
            'import-subnet',
            'export-subnet',
            'view-chart-subnet',
            'view-telephone',
            'create-telephone',
            'edit-telephone',
            'delete-telephone',
            'bulk-delete-telephone',
            'import-telephone',
            'export-telephone',
            'view-chart-telephone',
            'view-chart-company',
            'delete-profile-account',
            'logout-profile-sessions',
        ];

        foreach ($permissions as $permission) {
            Permission::create(['name' => $permission]);
        }
    }
}
